### ISSUE TITLE
Please deploy last changes

### ISSUE THREAD

**Issue by ApiShiro** [flutter-form-builder-ecosystem/form_builder_extra_fields#37]
## Environment

**Package version:**
v8.3.0 -> v8.4.0

## Description
Adaptive height for searchable dropdowns issue #8 added by #25

**What you'd like to happen:**
Deploy adaptive height pushed by #25

**Alternatives you've considered:**   
Pubspec looks currently like : 
```yml
#  form_builder_extra_fields: ^8.3.0
  form_builder_extra_fields:
    git:
      url: https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields
      ref: main
```

But it exposes my app to unwanted changes while it's not deployed.
