### ISSUE TITLE
Deploy package 8.4.0 - Error chip dependency

### ISSUE THREAD

**Issue by ApiShiro** [flutter-form-builder-ecosystem/form_builder_extra_fields#41]
## Environment

**Package version:**
v8.3.0 -> v8.4.0

## Description

**What you'd like to happen:**
Deploy package v8.4.0 (https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/pull/38)

**Alternatives you've considered:**   

```yaml
  form_builder_extra_fields:
    git:
      url: https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields
      ref: main
```

But it exposes my app to unwanted changes while it's not deployed.
